name: 'Test Dependency'
description: |
  Tests compiled dependency

inputs:
  name:
    description: Name of dependency
    required: true
  version:
    description: Version of dependency
    required: true
  dependency:
    description: path to dependency
    required: true
  mixins:
    description: json array containing additional package names needed to test dependency
    default: '[]'
    required: false
  required_dependency_1:
    description: path to additional dependency required for testing
    required: false
  required_dependency_2:
    description: path to additional dependency required for testing
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--name"
    - ${{ inputs.name }}
    - "--version"
    - ${{ inputs.version }}
    - "--dependency"
    - ${{ inputs.dependency }}
    - "--mixins"
    - ${{ inputs.mixins }}
    - "--required-dependency-1"
    - ${{ inputs.required_dependency_1 }}
    - "--required-dependency-2"
    - ${{ inputs.required_dependency_2 }}
