#!/usr/bin/env bash
set -euo pipefail

name=
version=
dependency=
mixins=
required_dependency_1=
required_dependency_2=

while test $# -gt 0; do
  case $1 in
    --name)
      name=$2
      shift
      ;;
    --version)
      version=$2
      shift
      ;;
    --dependency)
      dependency=$2
      shift
      ;;
    --mixins)
      mixins=$2
      shift
      ;;
    --required-dependency-1)
      required_dependency_1=$2
      shift
      ;;
    --required-dependency-2)
      required_dependency_2=$2
      shift
      ;;
    *)
      echo >&2 "Invalid argument: $1"
      exit 1
      ;;
  esac
  shift
done

if [[ "${name}" == "" || "${version}" == "" || "${dependency}" == "" ]]; then
  echo "Name, version, and dependency must be set"
  exit 1
fi

for mixin in $(echo ${mixins} | jq -r .[]); do
  if [[ $mixin = set:* ]]; then
    echo "This action does not support 'set:' mixins"
    exit 1
  elif [[ $mixin = run:* ]]; then
    continue
  elif [[ $mixin = build:* ]]; then
    package_names="${package_names} ${mixin#"build:"}"
  else
    package_names="${package_names} ${mixin}"
  fi
done

if [[ "${package_names}" != "" ]]; then
  apt-get -qqy update
  # shellcheck disable=SC2086
  apt-get -qqy install ${package_names}
fi

"dependency-tests/${dependency_name}/run" "${version}"

