name: 'Get Upstream Dependency'
description: |
  Gets upstream dependency version metadata

inputs:
  github-token:
    description: github access token
    required: false
  name:
    description: dependency name
    required: true
  version:
    description: dependency version
    required: true

outputs:
  uri:
    description: URI of upstream dependency
  sha256:
    description: SHA256 of upstream dependency
  release-date:
    description: Release date of upstream dependency
  deprecation-date:
    description: Deprecation date of upstream dependency

runs:
  using: 'composite'
  steps:
    - id: release-notes
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        go build -o /entrypoint "${{ github.action_path }}/entrypoint/main.go"

        metadata="$(/entrypoint \
          --github-token "${{ inputs.github-token }}" \
          --name "${{ inputs.name }}" \
          --version "${{ inputs.version }}"
        )"

        echo "::set-output name=uri::$(jq -r .uri <<< "${metadata}")"
        echo "::set-output name=sha256::$(jq -r .sha <<< "${metadata}")"
        echo "::set-output name=release-date::$(jq -r .release_date <<< "${metadata}")"
        echo "::set-output name=deprecation-date::$(jq -r .deprecation_date <<< "${metadata}")"

        rm -f /entrypoint
