name: node get new versions

on:
  workflow_dispatch: {}

jobs:
  check-node:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GAE_KEY }}

    - name: Get Known Versions
      id: known-versions
      run: |
        echo "set-output::known-versions='$(gsutil cat "gs://dependency-ci-artifacts/known-versions/node")'"

    - name: Get New Versions
      id: get-new-versions
      uses: ./actions/list-new-upstream-dependency-versions
      with:
        name: node
        known-versions: "${{ steps.known-versions.outputs.known-versions }}"

    - name: Trigger Builds
      run: |
        new_versions="${{ steps.get-new-versions.outputs.new-versions }}"
        for version in $(echo "${new_versions}" | jq -r .[]); do
          echo curl -X POST \
            https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \
                  \"event_type\": \"build\", \
                  \"client_payload\": { \
                    \"data\": { \
                      \"name\": \"node\", \
                      \"version\": \"${version}\" \
                     } \
                   } \
                 }"
        done

    - name: Updates Known Versions
      run: |
        echo "${{ steps.get-new-versions.outputs.upstream-versions }}" > known_versions
        gsutil cp known_versions "gs://dependency-ci-artifacts/known-versions/node"
