name: Test and Deploy Dep-Server

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

env:
  GAE_KEY: ${{ secrets.GAE_KEY }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:

  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v ./...

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GAE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy Server
      run: gcloud app deploy --quiet
