#@ load("@ytt:data", "data")
name: #@ data.values.name + " build"

#! "on" must be in quotes because it is a truthy in ytt
"on":
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
  repository_dispatch:
    types: [ build ]

env:
  DEP_NAME: #@ data.values.name
  VERSION: ${{ github.event.client_payload.version }}

jobs:
  #@yaml/text-templated-strings
  build-(@= data.values.name @):
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Set Env Vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        fi

    - name: Get upstream dependency
      id: get
      uses: ./actions/get-upstream-dependency
      with:
        name: "${{ env.DEP_NAME }}"
        version: "${{ env.VERSION }}"

    - name: Build
      id: build
      uses: ./actions/build-dependency
      with:
        name: "${{ env.DEP_NAME }}"
        version: "${{ env.VERSION }}"
        url: "${{ steps.get.outputs.uri }}"
        sha256: "${{ steps.get.outputs.sha256 }}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload dependency
      id: upload
      run: |
        artifact_path="${{ steps.build.outputs.artifact-path }}"
        filename="$(basename "${artifact_path}")"

        aws s3 cp "${artifact_path}" "s3://${{ secrets.DEPS_BUCKET }}/deps/${{ env.DEP_NAME }}/${filename}"

        uri="https://deps.paketo.io/${{ env.DEP_NAME }}/${filename}"
        echo "::set-output name=dependency-uri::${uri}"

    #@ if data.values.required_dependency != '':
    - name: Get required dependency
      id: required-dependency
      run: |
        uri="$(curl -sL "https://api.deps.paketo.io/v1/dependency?name=${{ env.DEP_NAME}}" | jq '. |= sort_by(.version) | reverse[0].uri')"
        echo "::set-output name=uri::${uri}"
    #@ end

    - name: Test
      uses: ./actions/test-dependency
      with:
        name: "${{ env.DEP_NAME }}"
        version: "${{ env.VERSION }}"
        dependency_url: "${{ steps.upload.outputs.dependency-uri }}"
        mixins: #@ data.values.mixins
        #@ if data.values.required_dependency != '':
        required_dependency: '${{ steps.required-dependency.outputs.uri }}'
        #@ end

    - name: Upload dependency metadata
      #@yaml/text-templated-strings
      run: |
        aws s3 cp "s3://${{ secrets.DEPS_BUCKET }}/metadata/${{ env.DEP_NAME }}.json" metadata.json

        metadata="$(cat << EOF
        {
          "name": "${{ env.DEP_NAME }}",
          "version": "${{ env.VERSION }}",
          "sha256": "${{ steps.build.outputs.sha256 }}",
          "uri": "${{ steps.upload.outputs.dependency-uri }}",
          "stacks": (@= data.values.stacks @),
          "source": "${{ steps.get.outputs.uri }}",
          "source_sha256": "${{ steps.get.outputs.sha256 }}",
          "deprecation_date": "${{ steps.get.outputs.deprecation-date }}"
        }
        EOF
        )"

        updated_metadata="$(jq --argjson metadata "${metadata}" --arg version "${{ env.version }}" -r 'del(.[] | select(.version == $version)) | [$metadata] + .' metadata.json)"

        echo "${updated_metadata}" > metadata.json

        aws s3 cp metadata.json "s3://${{ secrets.DEPS_BUCKET }}/metadata/${{ env.DEP_NAME }}.json"




