name: <NAME> get new versions

on:
  workflow_dispatch: {}

jobs:

  check:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:

    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GAE_KEY }}

    - name: Get Known Versions
      id: known-versions
      run: |
        echo "set-output::known-versions='$(gsutil cat "gs://dependency-ci-artifacts/known-versions/<NAME>")'"

    - name: Get New Versions
      id: get-new-versions
      uses: paketo-buildpacks/dep-server/actions/list-new-upstream-dependency-versions@migrate-dep-builder-to-gha
      with:
        name: "<NAME>"
        known-versions: "${{ steps.known-versions.outputs.known-versions }}"

    - name: Trigger Builds
      run: |
        new_versions="${{ steps.get-new-versions.outputs.new-versions }}"
        for version in $(echo "${new_versions}" | jq -r .[]); do
          curl -X POST \
            https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \
                  \"event_type\": \"build\", \
                  \"client_payload\": { \
                    \"data\": { \
                      \"name\": \"<NAME>\", \
                      \"version\": \"${version}\" \
                     } \
                   } \
                 }"
        done

    - name: Updates Known Versions
      run: |
        echo "\${{ steps.get-new-versions.outputs.known-versions }}" > known_versions
        gsutil cp known_versions gs://dependency-ci-artifacts/known-versions/"<NAME>"
